import type { Metadata } from "next";
import {manrope} from "@/utils/index";
import "./globals.css";
import Sidebar from "@/components/layout/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className} ${manrope.className} antialiased`}>
        <div className="wrapper flex">
          <Sidebar />
          <main className="flex-grow p-4">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
